
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode9.4

language: go

before_install:
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        cp misc/i2pd.osx.tar.gz ./i2pd.tar.gz &&
        tar xvf ./i2pd.tar.gz &&
    cp etc/i2pd/i2pd.samrtc.conf ./i2pd.conf; else
        sudo sed -i 's|xenial|bionic|g' /etc/apt/sources.list &&
        sudo apt-get update &&
        sudo apt-get dist-upgrade &&
        sudo apt-get install i2pd &&
        sudo cp etc/i2pd/i2pd.samrtc.conf /etc/i2pd/i2pd.conf;    fi

install:
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        sleep 10;
    make deps noopts; else
        sudo service i2pd start; sleep 10;
        make deps test noopts;
    sudo service i2pd stop; fi
